#!/usr/bin/env tsx
import { spawn } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.join(__dirname, '..')
const sampleDir = path.join(rootDir, 'sample-codebase')
const outputPath = path.join(rootDir, 'src', 'data', 'cliOutputs.ts')

interface RunResult {
  id: string
  tool: 'knip' | 'fallow'
  label: string
  command: string
  durationMs: number
  exitCode: number | null
  output: string
}

function runCommand(
  id: string,
  tool: 'knip' | 'fallow',
  label: string,
  command: string,
  args: string[],
  cwd: string,
): Promise<RunResult> {
  return new Promise((resolve) => {
    const start = performance.now()
    let stdout = ''
    let stderr = ''

    const child = spawn(command, args, {
      cwd,
      shell: true,
      env: process.env,
    })

    child.stdout?.on('data', (chunk: Buffer) => {
      stdout += chunk.toString()
    })
    child.stderr?.on('data', (chunk: Buffer) => {
      stderr += chunk.toString()
    })

    child.on('close', (exitCode) => {
      const output = [stdout.trim(), stderr.trim()].filter(Boolean).join('\n')
      resolve({
        id,
        tool,
        label,
        command: `${command} ${args.join(' ')}`,
        durationMs: Math.round(performance.now() - start),
        exitCode,
        output,
      })
    })
  })
}

function escapeTemplateLiteral(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

async function main() {
  console.log('Capturing CLI outputs...\n')

  const runs: RunResult[] = []

  runs.push(
    await runCommand(
      'knip',
      'knip',
      '未使用コード分析',
      'pnpm',
      ['exec', 'knip'],
      sampleDir,
    ),
  )
  runs.push(
    await runCommand(
      'fallow-full',
      'fallow',
      'フル分析',
      'pnpm',
      ['exec', 'fallow', '--summary'],
      sampleDir,
    ),
  )
  runs.push(
    await runCommand(
      'fallow-dead-code',
      'fallow',
      'Dead Code',
      'pnpm',
      ['exec', 'fallow', 'dead-code'],
      sampleDir,
    ),
  )
  runs.push(
    await runCommand(
      'fallow-dupes',
      'fallow',
      '重複検出',
      'pnpm',
      ['exec', 'fallow', 'dupes'],
      sampleDir,
    ),
  )
  runs.push(
    await runCommand(
      'fallow-health',
      'fallow',
      'ヘルス / 複雑度',
      'pnpm',
      ['exec', 'fallow', 'health'],
      sampleDir,
    ),
  )
  runs.push(
    await runCommand(
      'fallow-fix',
      'fallow',
      '自動修正プレビュー',
      'pnpm',
      ['exec', 'fallow', 'fix', '--dry-run'],
      sampleDir,
    ),
  )

  const benchmarkRuns = [
    await runCommand(
      'benchmark-knip',
      'knip',
      'Knip',
      'pnpm',
      ['exec', 'knip'],
      sampleDir,
    ),
    await runCommand(
      'benchmark-fallow-dead',
      'fallow',
      'Fallow dead-code',
      'pnpm',
      ['exec', 'fallow', 'dead-code', '--summary'],
      sampleDir,
    ),
    await runCommand(
      'benchmark-fallow-full',
      'fallow',
      'Fallow full',
      'pnpm',
      ['exec', 'fallow', '--summary'],
      sampleDir,
    ),
  ]

  const snapshots = runs.map(({ id, tool, label, command, durationMs, exitCode, output }) => ({
    id,
    tool,
    label,
    command,
    durationMs,
    exitCode: exitCode ?? 1,
    output,
  }))

  const benchmarkResults = benchmarkRuns.map(({ id, label, tool, durationMs, exitCode }) => ({
    id,
    label,
    tool,
    durationMs,
    exitCode: exitCode ?? 1,
  }))

  const fileContent = `// Auto-generated by scripts/capture-cli-outputs.ts — do not edit manually
// Regenerate: pnpm capture-outputs

export interface CliSnapshot {
  id: string
  tool: 'knip' | 'fallow'
  label: string
  command: string
  durationMs: number
  exitCode: number
  output: string
}

export interface BenchmarkResult {
  id: string
  label: string
  tool: 'knip' | 'fallow'
  durationMs: number
  exitCode: number
}

export const cliSnapshots: CliSnapshot[] = [
${snapshots
  .map(
    (s) => `  {
    id: ${JSON.stringify(s.id)},
    tool: ${JSON.stringify(s.tool)},
    label: ${JSON.stringify(s.label)},
    command: ${JSON.stringify(s.command)},
    durationMs: ${s.durationMs},
    exitCode: ${s.exitCode},
    output: \`${escapeTemplateLiteral(s.output)}\`,
  }`,
  )
  .join(',\n')}
]

export const benchmarkResults: BenchmarkResult[] = ${JSON.stringify(benchmarkResults, null, 2)}

export function getSnapshot(id: string): CliSnapshot | undefined {
  return cliSnapshots.find((s) => s.id === id)
}
`

  writeFileSync(outputPath, fileContent, 'utf8')

  for (const run of runs) {
    console.log(`  ✓ ${run.id} (${run.durationMs}ms, exit ${run.exitCode})`)
  }
  console.log(`\nWrote ${outputPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
