// Auto-generated by scripts/capture-cli-outputs.ts — do not edit manually
// Regenerate: pnpm capture-outputs

export interface CliSnapshot {
  id: string
  tool: 'knip' | 'fallow'
  label: string
  command: string
  durationMs: number
  exitCode: number
  output: string
}

export interface BenchmarkResult {
  id: string
  label: string
  tool: 'knip' | 'fallow'
  durationMs: number
  exitCode: number
}

export const cliSnapshots: CliSnapshot[] = [
  {
    id: "knip",
    tool: "knip",
    label: "未使用コード分析",
    command: "pnpm exec knip",
    durationMs: 518,
    exitCode: 1,
    output: `Unused files (2)
src/unused/orphanedWidget.tsx
src/utils/formatDateCopy.ts  
Unused dependencies (1)
lodash  package.json:10:6
Unused devDependencies (1)
@types/lodash  package.json:15:6
Unused exports (9)
getCartTotalWithBestDiscount  function  src/features/cart/cartStore.ts:21:17           
clearCart                     function  src/features/cart/cartStore.ts:25:17           
unusedCheckoutValidator       function  src/features/checkout/validateCheckout.ts:61:17
applyDiscount                 function  src/features/pricing/pricingEngine.ts:5:17     
unusedPricingHelper           function  src/features/pricing/pricingEngine.ts:24:17    
formatDateIso                 function  src/utils/helpers.ts:8:17                      
greetUser                     function  src/utils/helpers.ts:15:17                     
unusedHelper                  function  src/utils/helpers.ts:20:17                     
calculateTax                  function  src/utils/helpers.ts:24:17`,
  },
  {
    id: "fallow-full",
    tool: "fallow",
    label: "フル分析",
    command: "pnpm exec fallow --summary",
    durationMs: 314,
    exitCode: 1,
    output: `2  Unused files
       9  Unused exports
       1  Unused dependencies
       1  Unlisted dependencies
       1  Circular dependencies

      14  Total
       1  Clone families
       1  Clone groups
      34  Duplicated lines
   17.2%  Duplication rate
      24  Functions analyzed
       1  Above threshold
   85.2   Average maintainability (good)
■ Metrics: dead files 20.0% (2 of 10) · dead exports 32.1% (9 of 28) · MI 85.2 (good) · 1 circular dependency
  10 files analyzed
  1 entry point detected (1 default index)
  5 refactoring targets — start with src/features/pricing/pricingEngine.ts (dead code)

── Dead Code ──────────────────────────────────────
✗ 14 issues (0.02s)

── Duplication ────────────────────────────────────
✗ 17.2% duplication (0.00s)

── Complexity ─────────────────────────────────────
✓ 24 functions analyzed (0.00s)

Failed: dead-code (14 issues), dupes (1 clone groups), health (1 above threshold) — start with src/features/pricing/pricingEngine.ts`,
  },
  {
    id: "fallow-dead-code",
    tool: "fallow",
    label: "Dead Code",
    command: "pnpm exec fallow dead-code",
    durationMs: 297,
    exitCode: 1,
    output: `── Unused Code ─────────────────────────────────────

● Unused files (2)
  src/unused/orphanedWidget.tsx
  src/utils/formatDateCopy.ts
  Files not reachable from any entry point — https://docs.fallow.tools/explanations/dead-code#unused-files

● Unused exports (9)
  src/utils/helpers.ts (4)
    :8 formatDateIso
    :15 greetUser
    :20 unusedHelper
    :24 calculateTax
  src/features/cart/cartStore.ts (2)
    :21 getCartTotalWithBestDiscount
    :25 clearCart
  src/features/pricing/pricingEngine.ts (2)
    :5 applyDiscount
    :24 unusedPricingHelper
  src/features/checkout/validateCheckout.ts
    :61 unusedCheckoutValidator
  Exported symbols with no known consumers — https://docs.fallow.tools/explanations/dead-code#unused-exports
  To auto-fix: fallow fix --dry-run
  To suppress: // fallow-ignore-next-line unused-exports

── Dependencies ─────────────────────────────────────

● Unused dependencies (1)
  lodash
  Listed in dependencies but never imported — https://docs.fallow.tools/explanations/dead-code#unused-dependencies

● Unlisted dependencies (1)
  knip
  Packages imported in code but missing from package.json — https://docs.fallow.tools/explanations/dead-code#unlisted-dependencies

── Structure ─────────────────────────────────────

● Circular dependencies (1)
  src/features/cart/cartStore.ts
    → pricing/pricingEngine.ts → cartStore.ts

  Import cycles that can cause initialization failures and prevent tree-shaking — https://docs.fallow.tools/explanations/dead-code#circular-dependencies
1 entry point detected (1 default index)

✗ 2 files · 9 exports · 1 unused dependency · 1 unlisted dependency · 1 circular dependency (0.02s)`,
  },
  {
    id: "fallow-dupes",
    tool: "fallow",
    label: "重複検出",
    command: "pnpm exec fallow dupes",
    durationMs: 281,
    exitCode: 0,
    output: `● Duplicates (1 clone groups)

     17 lines  2 instances
    src/utils/formatDateCopy.ts:3-19
    src/utils/helpers.ts:1-17

  Identical code blocks detected via suffix-array analysis — https://docs.fallow.tools/explanations/duplication#clone-groups
✗ 34 lines (17.2%) duplicated across 2 files (0.00s)`,
  },
  {
    id: "fallow-health",
    tool: "fallow",
    label: "ヘルス / 複雑度",
    command: "pnpm exec fallow health",
    durationMs: 312,
    exitCode: 1,
    output: `● Health score: 30 F
  Deductions: unused deps -25.0 · circular deps -25.0 · duplication -10.0 · dead exports -6.4 · dead files -4.0
  Tip: add "dist" or "__generated__" to health.ignore in your config to exclude from duplication analysis

■ Metrics: 234 LOC · dead files 20.0% · dead exports 32.1% · avg cyclomatic 2.0 · p90 cyclomatic 2 · maintainability 85.2 (good) · 0 churn hotspots · 1 circular dep · 1 unused dep · duplication 17.2%

● High complexity functions (1)
  src/features/checkout/validateCheckout.ts
    :16 validateCheckout CRITICAL
          22 cyclomatic   33 cognitive   44 lines
         506.0 CRAP
  Functions exceeding cyclomatic, cognitive, or CRAP thresholds (https://docs.fallow.tools/explanations/health#complexity-metrics)

● File health scores (9 files) · sorted by triage concern

   79.2    src/features/checkout/validateCheckout.ts       risk
             64 LOC    1 fan-in    0 fan-out   50% dead  0.36 density  506.0 risk

   80.3    src/features/pricing/pricingEngine.ts           risk
             27 LOC    1 fan-in    1 fan-out   67% dead  0.22 density  20.0 risk

   77.6    src/utils/formatDateCopy.ts                     structure
             24 LOC    0 fan-in    0 fan-out  100% dead  0.17 density  2.0 risk

   78.8    src/unused/orphanedWidget.tsx                   structure
             10 LOC    0 fan-in    0 fan-out  100% dead  0.20 density  2.0 risk

   80.9    src/utils/helpers.ts                            structure
             27 LOC    2 fan-in    0 fan-out   80% dead  0.19 density  2.0 risk

   92.4    src/App.tsx                                     risk
             24 LOC    1 fan-in    4 fan-out    0% dead  0.08 density  6.0 risk

   84.2    src/features/cart/cartStore.ts                  structure
             28 LOC    2 fan-in    1 fan-out   50% dead  0.18 density  2.0 risk

   96.6    src/components/ProductCard.tsx                  risk
             11 LOC    1 fan-in    1 fan-out    0% dead  0.09 density  2.0 risk

   96.6    src/main.tsx                                    risk
              8 LOC    0 fan-in    1 fan-out    0% dead  0.13 density  2.0 risk

  Sorted by triage concern: the larger of low-MI concern and CRAP risk. The risk / structure tag marks which one placed each file. MI reflects complexity, coupling, and dead code; risk reflects untested complexity (CRAP) and can diverge from MI. Risk: low <15, moderate 15-30, high >=30. CRAP estimated from export references (85% direct, 40% indirect, 0% untested). Use --coverage for exact scores. https://docs.fallow.tools/explanations/health#file-health-scores

● Refactoring targets (5)
  2 low effort · 3 medium
    score = quick-win ROI (higher = better) · pri = absolute priority

   24.3  pri:24.3    src/features/pricing/pricingEngine.ts
         dead code · effort:low · confidence:high  Remove 2 unused exports to reduce surface area (67% dead)

   23.8  pri:23.8    src/features/checkout/validateCheckout.ts
         complexity · effort:low · confidence:high  Extract validateCheckout (cognitive: 33) in 64-LOC file into smaller functions

   13.9  pri:27.7    src/utils/helpers.ts
         dead code · effort:medium · confidence:high  Remove 4 unused exports to reduce surface area (80% dead)

   12.6  pri:25.1    src/utils/formatDateCopy.ts
         dead code · effort:medium · confidence:high  Remove 4 unused exports to reduce surface area (100% dead)

   11.4  pri:22.7    src/features/cart/cartStore.ts
         dead code · effort:medium · confidence:high  Remove 2 unused exports to reduce surface area (50% dead)

  Prioritized refactoring recommendations based on complexity, churn, and coupling signals — https://docs.fallow.tools/explanations/health#refactoring-targets
✗ 1 above threshold · 24 analyzed · maintainability 85.2 (good) (0.03s)`,
  },
  {
    id: "fallow-fix",
    tool: "fallow",
    label: "自動修正プレビュー",
    command: "pnpm exec fallow fix --dry-run",
    durationMs: 320,
    exitCode: 0,
    output: `Would remove export from src/features/pricing/pricingEngine.ts:24 \`unusedPricingHelper\`
Would remove export from src/features/pricing/pricingEngine.ts:5 \`applyDiscount\`
Would remove export from src/features/checkout/validateCheckout.ts:61 \`unusedCheckoutValidator\`
Would remove export from src/features/cart/cartStore.ts:25 \`clearCart\`
Would remove export from src/features/cart/cartStore.ts:21 \`getCartTotalWithBestDiscount\`
Would remove export from src/utils/helpers.ts:24 \`calculateTax\`
Would remove export from src/utils/helpers.ts:20 \`unusedHelper\`
Would remove export from src/utils/helpers.ts:15 \`greetUser\`
Would remove export from src/utils/helpers.ts:8 \`formatDateIso\`
Would remove \`lodash\` from dependencies in /workspace/sample-codebase/package.json
Dry run complete. No files were modified.`,
  }
]

export const benchmarkResults: BenchmarkResult[] = [
  {
    "id": "benchmark-knip",
    "label": "Knip",
    "tool": "knip",
    "durationMs": 506,
    "exitCode": 1
  },
  {
    "id": "benchmark-fallow-dead",
    "label": "Fallow dead-code",
    "tool": "fallow",
    "durationMs": 354,
    "exitCode": 1
  },
  {
    "id": "benchmark-fallow-full",
    "label": "Fallow full",
    "tool": "fallow",
    "durationMs": 334,
    "exitCode": 1
  }
]

export function getSnapshot(id: string): CliSnapshot | undefined {
  return cliSnapshots.find((s) => s.id === id)
}
